# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-14 05:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ntupa', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='cellphone',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='手機號碼'),
        ),
    ]
