# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-18 15:42
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('equip', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='名稱')),
                ('client', models.CharField(max_length=100, verbose_name='活動方名稱')),
                ('start_date', models.DateField(verbose_name='起始日期')),
                ('end_date', models.DateField(verbose_name='結束日期')),
                ('note', models.TextField(blank=True, verbose_name='備註')),
                ('assistant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assistant_events', to=settings.AUTH_USER_MODEL, verbose_name='主控助理')),
            ],
        ),
        migrations.AddField(
            model_name='equipment',
            name='last_updated',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 6, 18, 15, 42, 3, 206620, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100, verbose_name='名稱'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equip.Category', verbose_name='類型'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='condition',
            field=models.CharField(choices=[('良好', '良好'), ('損壞但堪用', '損壞但堪用'), ('損壞待修', '損壞待修'), ('報廢', '報廢')], max_length=100, verbose_name='機況'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='description',
            field=models.TextField(blank=True, verbose_name='備註'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='image',
            field=models.CharField(blank=True, max_length=200, verbose_name='圖片網址'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equip.Location', verbose_name='目前位置'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='manufacturer',
            field=models.CharField(max_length=100, verbose_name='製造商'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='model',
            field=models.CharField(max_length=100, verbose_name='型號'),
        ),
        migrations.AlterField(
            model_name='location',
            name='name',
            field=models.CharField(max_length=100, verbose_name='名稱'),
        ),
        migrations.AddField(
            model_name='event',
            name='equipments',
            field=models.ManyToManyField(to='equip.Equipment', verbose_name='借用器材'),
        ),
        migrations.AddField(
            model_name='event',
            name='manager',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manager_events', to=settings.AUTH_USER_MODEL, verbose_name='主控'),
        ),
        migrations.AddField(
            model_name='event',
            name='stages',
            field=models.ManyToManyField(related_name='stage_events', to=settings.AUTH_USER_MODEL, verbose_name='Stage'),
        ),
    ]
