# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-24 15:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equip', '0002_auto_20160618_2342'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='belongs_to',
            field=models.CharField(choices=[('PA 組', 'PA 組'), ('學生會', '學生會'), ('PA 社', 'PA 社'), ('不分國界', '不分國界'), ('其他', '其他')], default='', max_length=100, verbose_name='歸屬'),
            preserve_default=False,
        ),
    ]
