# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-01 17:27
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('equip', '0004_equipment_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='last_updated',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 7, 1, 17, 27, 1, 939363, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='assistant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assistant_events', to=settings.AUTH_USER_MODEL, verbose_name='主控助理'),
        ),
        migrations.AlterField(
            model_name='event',
            name='stages',
            field=models.ManyToManyField(blank=True, related_name='stage_events', to=settings.AUTH_USER_MODEL, verbose_name='Stage'),
        ),
    ]
